project: 
  type: website
  
website: 
  page-navigation: true
  title: "Pristine Seas Expedition- Palau (2024)" 
  site-url: "https://pristine-seas.github.io/exp-PLW-2024" 
  repo-url: https://github.com/pristine-seas/exp-PLW-2024
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
    
  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: bottom
    tools: 
      - icon: globe
        href: https://pristineseas.org
        text: "pristineseas.org"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Palau 2024 expedition"
      - icon: hdd
        href: "https://drive.google.com/drive/folders/1wFrwIccznqruKO5ViatH6onK5i0xCutd?usp=sharing"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Summary of work
      - href: 01_fish_surveys.qmd
        text: Fish Surveys

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
