---
title: "Palau 2024"
subtitle: "Data analyses"
author: "Juan Mayorga"
number-sections: false
date: today
theme: cosmo
format: 
  html:
    self-contained: true
    code-fold: true
    toc: true
    toc-location: right
---

```{r, message = F, warning = F, fig.width = 10, fig.height = 10, echo = F}
library(paletteer)
library(sf)
library(bigrquery)
library(gt)
library(tidyverse)

knitr::opts_chunk$set(eval = F, warning = F, message = F, include = F, echo = F)

PristineSeasR::set_ps_paths(email = "marine.data.science@ngs.org")

exp_id <- "PLW_2024"

exp_path <- file.path(ps_science_path, "expeditions", "PLW-2024")

ps_data_path <- file.path(ps_science_path, "datasets/")

bigrquery::bq_auth(email = "marine.data.science@ngs.org")

bq_connection <- DBI::dbConnect(bigrquery::bigquery(), project = "pristine-seas")
```

# Vessel track

```{r track, eval = TRUE}
#Argo mmsi: 312208000
#Argo callsign: V3OW5

argo_track <- sf::st_read(file.path(exp_path,
                                    "data/primary/raw/argo-route/data.geojson")) 

argo_nm <- round((st_length(argo_track)/10^3)*0.539957) # NM
```

The Argo traveled a total of `r round(as.numeric(sum(argo_nm)*1.852))` km^2^ during this expedition. 

```{r track_map, eval = TRUE, include = T}
mapview::mapview(argo_track, 
                 map.types = c("Esri.WorldImagery"))
```

# Summary of work

```{r exp_meta_tbl, eval = T, include = T}
expedition_meta <- tbl(bq_connection, "metadata.PLW_2024") |> 
  filter(location != "Transit") |> 
  collect()

#| column: page
expedition_meta |> 
  group_by(location, method) |> 
  summarize(n_sites = n_distinct(station_id)) |> 
  pivot_wider(names_from = location, 
              values_from = n_sites, 
              values_fill = 0) |> 
  gt::gt(rowname_col = "method") |> 
  grand_summary_rows(columns = everything(),
                     fns = list(list(label = md("**Grand total**"), fn = "sum")),
                     fmt = ~ fmt_number(., decimals = 0, use_seps = FALSE)) |> 
  tab_spanner(label = "SW Islands",
              columns = c("Sonsorol", "Fanna", "Pulo Anna", "Merir", "Tobi", "Helen")) |> 
  tab_spanner(label = "Offshore",
              columns = c("Babeldaob", "SW Slope", "NW Slope", "Seamount A", "Seamount B-N", "Seamount B-C", "Seamount B-S")) |> 
  tab_header(title = "Number of workstations per method and location") |> 
  opt_align_table_header(align = "left") |> 
  tab_style(locations = cells_grand_summary(),
            style = cell_fill(color = "lightblue" |> adjust_luminance(steps = +2))) |> 
  tab_options(ihtml.use_compact_mode = TRUE,
              data_row.padding = px(5)) 
```

```{r rov_map, eval = TRUE, include = T}
tmp <- expedition_meta |> 
  filter(!is.na(lon)) |> 
  collect() |> 
  st_as_sf(coords = c("lon", "lat"), crs = 4326) |> 
  group_by(method, ps_site_id, location, geometry) |> 
  summarize(strata = paste0(depth_m, "m",collapse = ", "))

mapview::mapview(tmp |> 
                   st_jitter(factor = 0.000005),
                 zcol = c(method = "method"), 
                 legend = TRUE,
                 alpha = 0.5,
                 col.regions = paletteer_d("MoMAColors::Klein", 11),
                 map.types = c("Esri.WorldImagery"),
                 layer.name = "method",
                 popup = leafpop::popupTable(tmp,
                                      zcol = c("method",
                                               "ps_site_id",
                                               "location",
                                               "strata")))
```
