---
title: "Palau 2024"
number-sections: false
date: today
theme: cosmo
format: 
  html:
    self-contained: true
    code-fold: true
    toc: true
    toc-location: right
---

```{r, message = F, warning = F, fig.width = 10, fig.height = 10, echo = F}
library(paletteer)
library(sf)
library(bigrquery)
library(gt)
library(tidyverse)

knitr::opts_chunk$set(eval = F, warning = F, message = F, include = F, echo = F)

PristineSeasR::set_ps_paths(email = "marine.data.science@ngs.org")

exp_id <- "PLW_2024"

exp_path <- file.path(ps_science_path, "expeditions", "PLW-2024")

ps_data_path <- file.path(ps_science_path, "datasets/")

bigrquery::bq_auth(email = "marine.data.science@ngs.org")

bq_connection <- DBI::dbConnect(bigrquery::bigquery(), project = "pristine-seas")
```

# Environmental DNA

## Metadata

```{r uvs, eval = TRUE}
uvs_meta <- readxl::read_xlsx(file.path(exp_path, 
                                        paste0("data/primary/raw/fish/",
                                               exp_id,
                                               "_fish_fieldbook_AMF.xlsx"))) |> 
  as_tibble()

uvs_meta <- uvs_meta |> 
  mutate(expedition = exp_id, 
         uvs_id = ps_station_id,
         date = lubridate::dmy(dd_mm_yyyy),
         local_time = hms::as_hms(local_time)) |> 
  select(expedition,  uvs_id, location, date, local_time, lat, lon, habitat, exposure, alternative_site_id, everything(), -dd_mm_yyyy, -sand_number, -sand_m, -ps_station_id, -team_lead)
```


```{r edna_clean, eval = TRUE, include = T}
eDNA_fieldbook <- readxl::read_xlsx(file.path(exp_path, 
                                        paste0("data/primary/raw/edna/",
                                               exp_id,
                                               "_edna_fieldbook.xlsx"))) |> 
  as_tibble() |> 
  mutate(expedition = exp_id, 
         method = "Environmental DNA",
         team_lead = "Molly Timmers",
         date = lubridate::ymd(date),
         across(c(filter_time, collection_time), hms::as_hms),
         depth_strata = if_else(depth_m < 1, "Surface", "Bottom"),
         ps_site_id = ps_station_id,
         paired_site_id = paired_station_id,
         station_id = paste(ps_site_id, 
                             if_else(depth_strata == "Surface", "s", "b"),
                             sep = "_"))

edna_meta <- eDNA_fieldbook |> 
  left_join(uvs_meta |> 
              select(uvs_id, location, habitat, exposure, lat, lon), 
            by = c("paired_site_id" = "uvs_id")) |>
  group_by(expedition, method, ps_site_id, location, date, lat, lon,
           habitat, exposure, station_id, depth_strata, depth_m, collection_time, filter_time,
           preservative,filter_type, site_photos, daily_negative, paired_site_id, team_lead) |> 
  summarize(n_replicates = n(),
            water_lts = sum(water_liters)) |> 
  relocate(c(paired_site_id, team_lead),  .after = last_col()) |> 
  ungroup()
```

```{r edna_map, eval = TRUE, include = T}
tmp <- edna_meta |> 
  filter(!is.na(lat)) |> 
  st_as_sf(coords = c("lon", "lat"), crs = 4326) |> 
  group_by(method, ps_site_id, location, habitat, exposure, geometry) |> 
  summarize(strata = paste0(depth_m, "m", collapse = ", "))

mapview::mapview(tmp,
                 zcol = c(exposure = "exposure"), 
                 legend = TRUE,
                 col.regions = paletteer_d("yarrr::nemo", 2),
                 map.types = c("Esri.WorldImagery"),
                 layer.name = "exposure",
                 popup = leafpop::popupTable(tmp,
                                      zcol = c("method",
                                               "ps_site_id",
                                               "location",
                                               "habitat",
                                               "exposure",
                                               "strata")))
```

```{r edna_table, eval = TRUE, include = T}
edna_meta |> 
  group_by(location, exposure, habitat) |> 
  summarize(strata = n_distinct(depth_strata),
            n_sites = n_distinct(ps_site_id),
            n_replicates = sum(n_replicates),
            n_water_lts = sum(water_lts)) |> 
  ungroup() |> 
  group_by(location) |> 
  gt::gt(rowname_col = "exposure", groupname_col = "location") |> 
  summary_rows(columns  = contains(c("n_", "_m")),
               fns = list(list(label = md("*Total*"), fn = "sum")),
               fmt = ~ fmt_number(., decimals = 0, use_seps = FALSE)) |> 
  grand_summary_rows(columns  = contains(c("n_", "_m")),
                     fns = list(list(label = md("**Grand total**"), fn = "sum")),
                     fmt = ~ fmt_number(., decimals = 0, use_seps = FALSE)) |> 
  tab_header(title = "eDNA samples per location, habitat, and exposure") |>
  opt_align_table_header(align = "left") |> 
  tab_style(locations = cells_summary(),
            style = cell_fill(color = "lightblue" |> adjust_luminance(steps = +1))) |> 
  tab_style(locations = cells_grand_summary(),
            style = cell_fill(color = "lightblue" |> adjust_luminance(steps = +2))) |> 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_row_groups()) |> 
  tab_options(ihtml.use_compact_mode = TRUE,
              data_row.padding = px(5)) |> 
  cols_label_with(fn = ~str_replace(.x, "n_", "# ") |> 
                    str_to_title()) |> 
  cols_label(ends_with("_lts") ~ "Water (l)")
```

```{r edna_export, eval = F}
bq_table_create(paste0("pristine-seas.metadata.",exp_id, "_edna"), 
                fields = as_bq_fields(edna_meta))

bigrquery::bq_table_upload(paste0("pristine-seas.metadata.",exp_id, "_edna"), 
                           values = edna_meta, fields = edna_meta)
```

